# action.yml
name: "Auto-reply to new issues"
description: "Post an auto-reply comment when a new issue is created"
inputs:
  issue-comment:
    description: "The comment to post on the new issue"
    required: true
    default: "Thank you for creating an issue! I typically address new issues on Thursdays. I'll get back to you as soon as I can. :clock1:"
runs:
  using: "composite"
  steps:
    - name: Post auto-reply comment
      uses: actions/github-script@v5
      with:
        script: |
          const issueComment = "${{ inputs.issue-comment }}";
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: issueComment,
          });
